config/routes.rb
Rails.application.routes.draw do
  root to: 'books#top'
  #get 'books/index' => 'books#index'
  #post 'books' => 'books#create'
  resources :books
  #delete 'books/:id' => 'books#destroy', as: 'destroy_book'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	validates :title, presence: true
	validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def top
  end

  def index
  	@books = Book.all
  	@book = Book.new
  end

  def show
  	@book = Book.find(params[:id])
  end

  def new
  	@book = Book.new
  end

  def create
  	@books = Book.all
  	@book = Book.new(book_params)
  	#book.save
  	#redirect_to book_path(book.id)
  	if @book.save
  	   flash[:notice] = "Book was successfully created."
  	   redirect_to book_path(@book.id)

    else
    	render "index"
    end

  end

  def edit
  	@book = Book.find(params[:id])

  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
    flash[:notice] = "Book was successfully updated."
    redirect_to book_path(@book.id)
else
	render "edit"
  end
end

  def destroy
  	book = Book.find(params[:id])
  	book.destroy
  	flash[:notice] = "Book was successfully destroyed."
  	redirect_to books_path
  end

  private
  def book_params
  	params.require(:book).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<% if @book.errors.any? %>
	<% if @book.errors.count >= 2 %>
	<h2><%= @book.errors.count %>errors prohibited this book from being saved:</h2>
	<% else %>

	<h2><%= @book.errors.count %>error prohibited this book from being saved:</h2> 
	<% end %>
    <ul>
        <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
    </ul>
    <% end %>
<%#= form_for(@book, url: '/books') do |f| %>
<%= form_for(@book) do |f| %>

<h4>Title</h4>
<%= f.text_field :title %>

<h4>Body</h4>
<%= f.text_field :body %>

<br><%= f.submit 'Update Book' %></br>

<% end %>

<%= link_to "show", book_path(@book) %>

<%= link_to "back", books_path %>

app/views/books/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" type="text/css" href="">
	<title>Bookers</title>
</head>
  <body>
  	<%= flash[:notice] %>
	<h1>Books</h1>
	<table>
		<thead>
			<tr>
				<th>Title</th>
				<th>Body</th>
				<th colspan="3"></th>
			</tr>
		</thead>
				<tbody>
					<% @books.each do |book| %>
					<tr>
					<td><%= book.title %></td>
					<td><%= book.body %></td>
					<td><%= link_to "show", book_path(book.id) %></td>
		            <td><%= link_to "edit", edit_book_path(book.id) %></td>
		            <td><%= link_to "destroy", book_path(book), method: :delete, "data-confirm" => "Are you sure?" %></td>
					</tr>
			        <% end %>
		        </tbody>
	</table>
	<h2>New book</h2>
	  <% if @book.errors.any? %>
	  <% if @book.errors.count >= 2 %>
	  <h3><%= @book.errors.count %>errors prohibited this book from being saved:</h3>
	  <% else %>

	  <h3><%= @book.errors.count %>error prohibited this book from being saved:</h3> 
	  <% end %>
      <ul>
      <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
      </ul>
      <% end %>
	  <%= form_for(@book) do |f| %>

	<h4>Title</h4>
	<%= f.text_field :title %>

	<h4>Body</h4>
	<%= f.text_field :body %>

	<br><%= f.submit 'Create Book' %></br>

	<% end %>
   </body>
</html>

app/views/books/new.html.erb
<h3>New book</h3>
<%= form_for(@book, url: '/books') do |f| %>

<h4>Title</h4>
<%= f.text_field :title %>

<h4>Body</h4>
<%= f.text_field :body %>

<%= f.submit 'Create Book' %>
<% end %>

app/views/books/show.html.erb
<%= flash[:notice] %>

<h2>title</h2>

<p><%= @book.title %></p>
<h2>body</h2>
<p><%= @book.body %></p>

<%= link_to "edit", edit_book_path(@book) %>
      <!-- <a href="#">削除</a> を削除し、以下コードに変更 -->
<%= link_to "back", books_path %>

app/views/books/top.html.erb
<h1>ようこそ　Bookersへ！</h1>
<p>Bookersでは、さまざまな書籍に関するあなたの意見や<br>
印象を共有し交換することができます</p>

<a href="/books">start</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>